### PR TITLE
New (Q)Unit Test plugin

### PR DESCRIPTION
**Pull request by cubitouch**
New Unit Test plugin that allow to run QUnit tests from dashboard to client and display results.
It support drag-n-drop, file picking and manual writing.
https://github.com/MicrosoftDX/Vorlonjs/issues/142

### CODE REVIEW

**Comment by pierlag** [comment]
Hi, 
Can you add a demo page in sample folder ?

Thanks

**Comment by deltakosh** [comment]
Please merge on rev branch

**Comment by cubitouch** [comment]
@pierlag: What do you need as a sample? A page with an input and a value I would check in a test?
Since the test is run from dashboard, it is difficult to have a complete client sample...

**Comment by pierlag** [comment]
Not complete test juste a sample page to demonstrate the plug-in

**Comment by pierlag** [comment]
Can you change the Pull request on dev branch and add a sample html page to demonstrate this new plugin
thanks

**Comment by cubitouch** [comment]
Yes off course, I will do it ASAP :)

**Comment by cubitouch** [comment]
Reopened at https://github.com/MicrosoftDX/Vorlonjs/pull/162

**Pull request closed without merging**
