### PR TITLE
DOM Explorer and console plugin improvements

### PR DESCRIPTION
**Pull request by gleborgne**
edit attributes and text in DOM explorer
messaging with commands
handle objects in console plugin
handle console.dir in console plugin
handle filtering in console plugin

### CODE REVIEW

**Comment by deltakosh** [comment]
Could please remove generated CSS?

**Comment by deltakosh** [comment]
Can you also update the whatsnew file to keep track of all additions :) ?

**Comment by gleborgne** [comment]
it's done

**Comment by gleborgne** [comment]
done also :-)

**Comment by deltakosh** [comment]
Feedbacks:
- Refresh icon (the round stuff) does not work on Chrome
- I do not get why there is a dashed line under the text
- Could you please revert +/- icon to previous version (without the square)

EXCELLENT JOB BTW!

**Comment by deltakosh** [comment]
Ho can I remove an attribute?

**Comment by gleborgne** [comment]
By removing attribute name (works that way in Chrome and FF dev Tools)

**Comment by gleborgne** [comment]
Dashed line indicate that element is in update mode. We will work on other issues :)

**Comment by deltakosh** [comment]
Humm. That's not obvious for sure. And if you click on various nodes the dashed lines sometimes remains

**Pull request merged**
