### PR TITLE
[Desktop] - Make text selectable + Enhance the context menu

### PR DESCRIPTION
**Pull request by PaulFasola**

### CODE REVIEW

**Comment by PaulFasola** [comment]
#385

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by meulta** [comment]
Thx! Unable to build it right now, can you check?

**Comment by meulta** [comment]
? :)

**Comment by meulta** [comment]
no anwers, closing this. Reopen if any news.

**Pull request closed without merging**
