### PR TITLE
Bind vorlon current instance location to the dashboard

### PR DESCRIPTION
**Pull request by dhoko**
From:

```
TO GET STARTED, YOU MUST ADD A REFERENCE TO CLIENT SCRIPT IN THE PAGE OF YOUR WEBSITE, LIKE THIS :
<script src="http://localhost:1337/vorlon.js"></script>
```

To:
```
TO GET STARTED, YOU MUST ADD A REFERENCE TO CLIENT SCRIPT IN THE PAGE OF YOUR WEBSITE, LIKE THIS :
<script src="{http|https}://{ip}:{port:vorlon}/vorlon.js"></script>
```

*I don't run Vorlon with the default port and from localhost :balloon:*

### CODE REVIEW

**Comment by meulta** [comment]
Can you please sign the cla? :)

**Comment by dhoko** [comment]
Cla?
Le 2 juil. 2015 2:37 PM, "Etienne Margraff" <notifications@github.com> a
écrit :

**Comment by cubitouch** [comment]
"Contribution License Agreement", see the message above from @msftclas :)

**Comment by deltakosh** [comment]
Two warnings:
Do not edit .js but .ts
Please commit on development branch

**Comment by meulta** [comment]
@dhoko  any news? :) Can you make that PR to the dev branch ?

**Comment by dhoko** [comment]
@meulta Yup I'm reading the cla. You guys are crazy :)

**Comment by dhoko** [comment]
Do I have to sign the CLA ?

**Comment by deltakosh** [comment]
Everyone has to sign it:)

**Comment by dhoko** [comment]
cf #161

**Pull request closed without merging**
