### PR TITLE
New (Q)Unit Test plugin

### PR DESCRIPTION
**Pull request by cubitouch**
New Unit Test plugin that allow to run QUnit tests from dashboard to
client and display results.
It support drag-n-drop, file picking and manual writing.
#142

### CODE REVIEW

**Comment by pierlag** [comment]
Thanks @cubitouch

**Comment by deltakosh** [comment]
Hey do you mind writing a little doc/blog about your plugin?

**Comment by cubitouch** [comment]
Off course :)

What material do you need and where would you publish it ?

**Comment by deltakosh** [comment]
You can either write it on your own blog and we will link it or see with @meulta :)

**Comment by cubitouch** [comment]
Oh ok, that's already in the stack, sir :)
I will probably publish these (one by plugin) at the begining of September.

**Comment by deltakosh** [comment]
Lovely! I will then link it from the doc!

**Comment by cubitouch** [comment]
This is a french blog actually, but I can translate it if you want

-----Message d'origine-----
De : "David Catuhe" <notifications@github.com>
Envoyé : ‎06/‎08/‎2015 19:20
À : "MicrosoftDX/Vorlonjs" <Vorlonjs@noreply.github.com>
Cc : "Hugo CARNICELLI" <hugocarnicelli@gmail.com>
Objet : Re: [Vorlonjs] New (Q)Unit Test plugin (#162)

Lovely! I will then link it from the doc!

**Comment by deltakosh** [comment]
It could be sweet:)

**Pull request merged**
