### PR TITLE
Added ability to check if client plugins are ready and fixed issues with isReady()

### PR DESCRIPTION
**Pull request by mlucool**

### CODE REVIEW

**Comment by mlucool** [comment]
@meulta can you please take a look at this?

**Comment by meulta** [comment]
I will :)

**Comment by mlucool** [comment]
@meulta do you know when you will have a chance to look at this?

**Comment by mlucool** [comment]
@meulta thanks! Do you know when this will be released?

**Comment by meulta** [comment]
Should be next week :)

**Comment by meulta** [comment]
Done! https://www.npmjs.com/package/vorlon

**Pull request merged**
