### PR TITLE
UI improvement

### PR DESCRIPTION
**Pull request by gleborgne**
remove jquery UI accordion in DOM explorer
add landing page in dashboard

### CODE REVIEW

**Comment by gleborgne** [comment]
added layout panel in DOM explorer

**Comment by meulta** [comment]
Hey,
Great work :)
Refresh button indicator and autorefresh mode does not seem to work anymore. Does it on your side?
Thanks

**Comment by gleborgne** [comment]
it's ok now

**Comment by meulta** [comment]
Great!

**Pull request merged**
