### PR TITLE
Network Monitor and Resources Explorer plugins

### PR DESCRIPTION
**Pull request by cubitouch**
Cleaner PR with a little bonus :)
https://github.com/MicrosoftDX/Vorlonjs/issues/95
https://github.com/MicrosoftDX/Vorlonjs/issues/88

### CODE REVIEW

**Comment by davrous** [comment]
Hi! I've started reviewing quickly the code. I'll spend more time on it tomorrow. Thanks for this contribution. :)

**Comment by cubitouch** [comment]
Great news ;)
Let me know when you need me to rebase so you can merge it.

**Comment by deltakosh** [comment]
Can you please rebase it now?

**Comment by cubitouch** [comment]
Done. I'm not used to git... I feel like I messed it up again x)

**Comment by davrous** [comment]
Currently testing it. It's very very cool!!! :) Would be great to work on IndexedDB for the resource tab in a future update.

Need to do a couple of other tests and I'll will merge it.

**Comment by cubitouch** [comment]
Great !

About the resources panel and IndexedDB, since there isn't any way to enumerate databases from client side (as I found), I have thought about an input dashboard side for the database name (and probably also a query input). I will probably start from here :)

**Comment by deltakosh** [comment]
I'm so sorry but I need you to rebase as we changed the way plugins work (two files)...Once done, I'll validate immediatly

**Comment by cubitouch** [comment]
I'll create a new one :')

**Pull request closed without merging**
