### PR TITLE
Master

### PR DESCRIPTION
**Pull request by gleborgne**
adding a new plugin and generalizing some common styles like font for code, buttons, ...

### CODE REVIEW

**Comment by csuwildcat** [comment]
@deltakosh --> I have this string of commits running on a separate branch, and everything seems to work and I have observed no errors during use of the Object Explorer plugin. One question: what type of code review are you looking for? I wasn't sure whether we have a style guide or any measure by which to evaluate it.

**Comment by deltakosh** [comment]
Mainly check coherence, naming conventions (same as other piece of code), visual design, tab and spaces.
But honestly I already know that this will be ok for this specific PR:)

A local readme would be great also in order to update the doc

**Comment by gleborgne** [comment]
Hi, I've Just added a couple commits to polish a little more, and added font-awesome for iconography (according to discussions with @deltakosh)

**Comment by csuwildcat** [comment]
Everything appears to be in order. But I must admit, I am rather new to TypeScript, so while I have managed to write with it to get stuff into the project, I don't have the most attuned eye for best practices and code hygiene. 

Merging.

**Comment by csuwildcat** [comment]
I am now seeing the Obj Explorer endlessly spinning - you seeing that @gleborgne?

**Comment by csuwildcat** [comment]
Hmm, restarted the local build again and it is now working. Not sure what that was about, but let's monitor this to ensure there's not some intermittent bug.

**Comment by gleborgne** [comment]
I've seen it once after having a JavaScript error in DOM explorer (cannot get property border of undefined). After that error the websocket got out of order. Their should be a general reflection on error management in the communication pipeline. I haven't looked much at that part for now and, as an outsider, I prefer discussing architecture with the team before touching anything.
________________________________

**Pull request merged**
