### PR TITLE
introducing Vorlon to components

### PR DESCRIPTION
**Pull request by csuwildcat**
Big commit, but mostly builder and dependencies - here's what it contains:

X-Tag uses Grunt to compile the polyfill for Custom Elements, the library, and all the components you include, it also used Bower to define dependencies.

Almost all of the files additions are those new lib/polyfills.

As a first addition, I added a notification component to the Core object, and it knows when to use a component in the dashboard vs a vanilla div in the client. This new component can be called via Core's messaging functions from wherever that object can be accessed.

Next up: codify the tools bar used in Object Explorer into a component that can be used easily across plugins, and add a listener for a refresh call that spans across plugins. Authors can raise the event directly, or expose a refresh control element that raises one based on user input (a click-to-refresh button, for instance). That last part is to close out the bugs surrounding DOM watching and auto refreshing content from the client.

Please pull in this branch to your own repos for testing, I want to make sure nothing has regressed that I didn't catch. Presently it throws no errors, and is working as expected, but I am counting on you to kick the tires.

### CODE REVIEW

**Comment by csuwildcat** [comment]
@deltakosh would be good to have you pull this into your personal branch as well, more eyes the better.

**Comment by deltakosh** [comment]
Why using Grunt as we already use Gulp? Can we stay with just gulp? Some for Bower. I'm not for multiplying task and packages managers

**Comment by csuwildcat** [comment]
@deltakosh I'd have to redo all the code that does dependency resolution, file ordering, etc. I can do that, but it's going to add a lot of time. Your call. Another option is that I always just check in a compiled JS and CSS file, exclude all generator files, dependencies, etc. from Vorlon, and we treat it like a single repo that brings in those 2 completed files. Thoughts?

**Comment by csuwildcat** [comment]
This is really the issue with all builders - as soon as you want to use another project inside your own, it has the extra baggage :/

**Comment by csuwildcat** [comment]
@deltakosh could start a new repo under DX called VorlonComponents, toss it in there, and pull its output files into Vorlon.

**Comment by deltakosh** [comment]
I prefer the option to just get the 2 completed files. This is by far simpler. I do not want to add 200% more files just because we use GUlp and X-Tag uses Grunt :)

**Comment by csuwildcat** [comment]
@deltakosh will do, I completely agree. It also makes components easier to reason about when they're not nested 50 layers deep in the project. As components, they should be thought of as project agnostic anyway, so it makes a lot of sense.

Look for another in-bound commit this evening.

**Comment by deltakosh** [comment]
Agree! In the meantime, please create a "Components" branch for this experiment. It will be easier to work with then :)

**Comment by csuwildcat** [comment]
Woops, I forgot to do it as a branch, I'll do another pull request.

**Pull request closed without merging**
