### PR TITLE
Enable serving static resources from baseUrl Issue#115

### PR DESCRIPTION
**Pull request by mauron85**
More details in here:
https://github.com/MicrosoftDX/Vorlonjs/issues/115

Example of nginx conf
```
Here is my nginx conf:

server {
    listen              80;
    listen              [::]:80;
    server_name         some.server.com;
    root                /var/www;

     location /socket.io/ {
             proxy_pass http://localhost:1337;
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection "upgrade";
             proxy_set_header Host $host;
    }

    location ^~ /vorlonjs/ {
         proxy_pass       http://localhost:1337;
         proxy_set_header Host      $host;
         proxy_set_header X-Real-IP $remote_addr;
    }
}
```

### CODE REVIEW

**Comment by deltakosh** [comment]
Hello can you resync your PR?

**Comment by mauron85** [comment]
Hi, do you mean to resync with some specific branch?

**Comment by deltakosh** [comment]
Yes I cannot merge now

**Comment by mauron85** [comment]
Ok. New PR synced with development-0.0.16 branch

https://github.com/MicrosoftDX/Vorlonjs/pull/211

**Pull request closed without merging**
