### PR TITLE
Add start/end tag highlighting on hover

### PR DESCRIPTION
**Pull request by csuwildcat**
This pull provides tag-matched highlighting on hover to more easily understand the scope of content sections.

### CODE REVIEW

**Comment by deltakosh** [comment]
Huge!!

**Comment by csuwildcat** [comment]
@davrous before merging this, can you run it to take a look at the error feedback in the console on build? TypeScript is complaining about nodes that aren't type-declared, but I don't know how to do the inline declarations.

**Comment by csuwildcat** [comment]
@deltakosh nothing is broken in it, but I got a few compiler complaints about types - more of the TypeScript compiler not knowing the type that will be accessed via an event property. How do you declare types inline? For instance: 

`node.parentNode.parentNode ...` doing anything like this seems to complain because TypeScript doesn't know that those nodes are going to be HTMLElement instances. Is there a way to tag that getter chain with some kind of "ignore this, I know the types are right"?

**Comment by deltakosh** [comment]
You should not ignore but cast them like I did for HtmlElement

**Comment by csuwildcat** [comment]
@deltakosh does that mean every step of the getter chain needs to be cast to a `var` before access? Like this:

```javascript
var parent = <HTMLElement>node.parentNode;
var nextParent = <HTMLElement>parent.parentNode;
nextParent.setAttribute(...);
```

I was hoping for a better syntax for multi-step getter chains.

**Comment by deltakosh** [comment]
I've just checked in the fix so you can see what I mean

**Comment by deltakosh** [comment]
this is because parent can be something else than a HtmlElement

**Comment by csuwildcat** [comment]
Yeah, I figured it would require breaking the declaration out into a separate `var`. It's a shame there's no way to assert a type for an entire chain of nodes/accessors; for instance, something like this pseudo code:

`(<HTMLElement>node.parentNode.parentNode).setAttribute(...);`

**Comment by deltakosh** [comment]
This should work

**Comment by csuwildcat** [comment]
@deltakosh wow, it does, that's easier!

**Pull request merged**
