### PR TITLE
Build catalog

### PR DESCRIPTION
**Pull request by deltakosh**
Allows users to define plugins they want to use

### CODE REVIEW

**Comment by deltakosh** [comment]
@csuwildcat: Can you help merging the control.css for DOM Explorer and do final testing?

**Comment by csuwildcat** [comment]
I've pulled the BuildCatalog branch in and merged the CSS file, and everything appears to be working ok, but the Modernizr plugin no longer shows in the UI - is that expected?

**Comment by deltakosh** [comment]
No:)

**Comment by deltakosh** [comment]
Did you check on the bottom tabs?

**Comment by csuwildcat** [comment]
LOL, duh, it's right there in the bottom tabs - my eyes just hopped over it! :)

**Comment by deltakosh** [comment]
@meulta needs to document it:)

**Pull request merged**
