### PR TITLE
DOM Explorer tree view enahancements

### PR DESCRIPTION
**Pull request by csuwildcat**
I have added the following to the tree view portion of the DOM Explorer:
- Updated styles
- Moved many needless elements to be represented as CSS pseudo elements
- Expand and collapse of the DOM tree is now purely selector/attribute based, no more inline styles setting
- Text nodes are now shown
- Keyboard controls are enabled for expanding and collapsing branches in the tree, and showing styles of a node in the CSS panel
- Many events moved to delegation, for performance reasons

### CODE REVIEW

**Comment by meulta** [comment]
Hey,

seem to be a compilation error using gulp in the plugins folder.
Does it work on your side?

thanks

**Comment by csuwildcat** [comment]
@meulta I believe it's the TypeScript transpiler errantly complaining about EventTarget not having a property, but that's not the case. I don't know how why the transpiler is flagging that, but I'm 99% sure it's wrong to do so.

**Comment by csuwildcat** [comment]
@meulta here is the line it is complaining about, which works just fine in the build, but seems to give the transpiler fits: https://github.com/csuwildcat/Vorlonjs/commit/0657263e054fcf4d7a39c52ac66a98a0f1dd1efb#diff-b30fa2ba8cc4627aac523e9a74f5ce48R223

**Comment by deltakosh** [comment]
I have the same issue

**Pull request merged**
