### PR TITLE
DOM Explorer & Console plugin

### PR DESCRIPTION
**Pull request by gleborgne**
fix console.dir bug
fix dom explorer bug occuring when changing styles
add search by css selector
add auto refresh based on mutation observer

### CODE REVIEW

**Comment by deltakosh** [comment]
Did you check performance of the auto-refresh? Mostly on android phone we had to remove it previous due to perf issue. I'm afraid this is gonna be the same here. This is why we had to implement the refresh on demand

**Comment by gleborgne** [comment]
Checked on a low end Android device and worked well...

**Comment by deltakosh** [comment]
Waiting for your feedback on low end devices AND really dynamic or he DOM sites

**Comment by gleborgne** [comment]
tryed it on real website with a real device

**Comment by deltakosh** [comment]
So we are good to go :)

**Pull request merged**
