### PR TITLE
Device plugin

### PR DESCRIPTION
**Pull request by colbin8r**
Added a new Device plugin that gives information about the client device, including:

* Viewport properties
* Screen size
* Resolution
* Pixel ratio
* Root font size
* User agent

It is heavily inspired by http://mydevice.io/. The plugin is enabled by default in Core.

### CODE REVIEW

**Comment by colbin8r** [comment]
As an MS intern, do I need still need to go through the CLA process, or can I go ahead and merge this in?

**Comment by meulta** [comment]
Hey Colby, 

I do not see any information on the tabl eon the Device info tab. The label are here but not the content.
Can you have a look?

Thanks

**Comment by colbin8r** [comment]
@meulta looks like the problem stemmed from a .gitignore preventing the dependent libraries from being added to version control. I have corrected the problem. Can you try again and let me know your results?

**Comment by meulta** [comment]
Great

**Pull request merged**
